// <auto-generated />
namespace Logics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewOne5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewOne5));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071538083_NewOne5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
